add dist

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -49,17 +49,21 @@ jobs:
         with:
           ref: gh-pages
           fetch-depth: 0
-
-      - name: Configuration environment
-        run: |
-          mkdir -p ~/.ssh/
-          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
-          chmod 600 ~/.ssh/id_rsa
-          ssh-keyscan mrhope.site >> ~/.ssh/known_hosts
-          git config --global user.name 'Mr.Hope'
-          git config --global user.email 'mister-hope@outlook.com'
-
-      - name: Deploy
-        run: |
-          git push -f git@mrhope.site:/www/wwwroot/mrhope gh-pages
-          ssh git@mrhope.site "cd /www/wwwroot/mrhope && git reset --hard HEAD"
+    - name: Commit documentation changes
+      run: |
+        git clone https://github.com/${{ github.repository }}.git --branch gh-pages --single-branch gh-pages
+        cp -r dist/* gh-pages/
+        cd gh-pages
+        touch .nojekyll
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Update documentation" -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # that.
+    - name: Push changes
+      uses: ad-m/github-push-action@master
+      with:
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.GITHUB_TOKEN }}
